/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as ReactFormRouteImport } from './routes/reactForm'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReactFormIndexRouteImport } from './routes/reactForm.index'
import { Route as ReactFormSummaryRouteImport } from './routes/reactForm.summary'

const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const ReactFormRoute = ReactFormRouteImport.update({
  id: '/reactForm',
  path: '/reactForm',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReactFormIndexRoute = ReactFormIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReactFormRoute,
} as any)
const ReactFormSummaryRoute = ReactFormSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => ReactFormRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reactForm': typeof ReactFormRouteWithChildren
  '/todos': typeof TodosRoute
  '/reactForm/summary': typeof ReactFormSummaryRoute
  '/reactForm/': typeof ReactFormIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/todos': typeof TodosRoute
  '/reactForm/summary': typeof ReactFormSummaryRoute
  '/reactForm': typeof ReactFormIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reactForm': typeof ReactFormRouteWithChildren
  '/todos': typeof TodosRoute
  '/reactForm/summary': typeof ReactFormSummaryRoute
  '/reactForm/': typeof ReactFormIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reactForm'
    | '/todos'
    | '/reactForm/summary'
    | '/reactForm/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/todos' | '/reactForm/summary' | '/reactForm'
  id:
    | '__root__'
    | '/'
    | '/reactForm'
    | '/todos'
    | '/reactForm/summary'
    | '/reactForm/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReactFormRoute: typeof ReactFormRouteWithChildren
  TodosRoute: typeof TodosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reactForm': {
      id: '/reactForm'
      path: '/reactForm'
      fullPath: '/reactForm'
      preLoaderRoute: typeof ReactFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reactForm/': {
      id: '/reactForm/'
      path: '/'
      fullPath: '/reactForm/'
      preLoaderRoute: typeof ReactFormIndexRouteImport
      parentRoute: typeof ReactFormRoute
    }
    '/reactForm/summary': {
      id: '/reactForm/summary'
      path: '/summary'
      fullPath: '/reactForm/summary'
      preLoaderRoute: typeof ReactFormSummaryRouteImport
      parentRoute: typeof ReactFormRoute
    }
  }
}

interface ReactFormRouteChildren {
  ReactFormSummaryRoute: typeof ReactFormSummaryRoute
  ReactFormIndexRoute: typeof ReactFormIndexRoute
}

const ReactFormRouteChildren: ReactFormRouteChildren = {
  ReactFormSummaryRoute: ReactFormSummaryRoute,
  ReactFormIndexRoute: ReactFormIndexRoute,
}

const ReactFormRouteWithChildren = ReactFormRoute._addFileChildren(
  ReactFormRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReactFormRoute: ReactFormRouteWithChildren,
  TodosRoute: TodosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
