/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as ReactFormtwoRouteImport } from './routes/reactFormtwo'
import { Route as ReactFormRouteImport } from './routes/reactForm'
import { Route as IndexRouteImport } from './routes/index'

const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const ReactFormtwoRoute = ReactFormtwoRouteImport.update({
  id: '/reactFormtwo',
  path: '/reactFormtwo',
  getParentRoute: () => rootRouteImport,
} as any)
const ReactFormRoute = ReactFormRouteImport.update({
  id: '/reactForm',
  path: '/reactForm',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reactForm': typeof ReactFormRoute
  '/reactFormtwo': typeof ReactFormtwoRoute
  '/todos': typeof TodosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reactForm': typeof ReactFormRoute
  '/reactFormtwo': typeof ReactFormtwoRoute
  '/todos': typeof TodosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reactForm': typeof ReactFormRoute
  '/reactFormtwo': typeof ReactFormtwoRoute
  '/todos': typeof TodosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/reactForm' | '/reactFormtwo' | '/todos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/reactForm' | '/reactFormtwo' | '/todos'
  id: '__root__' | '/' | '/reactForm' | '/reactFormtwo' | '/todos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReactFormRoute: typeof ReactFormRoute
  ReactFormtwoRoute: typeof ReactFormtwoRoute
  TodosRoute: typeof TodosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reactFormtwo': {
      id: '/reactFormtwo'
      path: '/reactFormtwo'
      fullPath: '/reactFormtwo'
      preLoaderRoute: typeof ReactFormtwoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reactForm': {
      id: '/reactForm'
      path: '/reactForm'
      fullPath: '/reactForm'
      preLoaderRoute: typeof ReactFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReactFormRoute: ReactFormRoute,
  ReactFormtwoRoute: ReactFormtwoRoute,
  TodosRoute: TodosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
